<?php
namespace BfCamel\CRM\Admin;

use BfCamel\CRM\CRM\NoteService;
use BfCamel\CRM\CRM\SubmissionService;
use BfCamel\CRM\CRM\TagService;
use BfCamel\CRM\CRM\WorkflowService;
use BfCamel\CRM\Database\Schema;
use BfCamel\CRM\Forms\Repository;

if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SubmissionsPage {
    private static $instance = null;
    public static function instance() { if ( null === self::$instance ) self::$instance = new self(); return self::$instance; }
    private function __construct() {}

    public function page() {
        $this->guard( 'bfcamel_crm_view_submissions' );
        $id = isset( $_GET['id'] ) ? absint( $_GET['id'] ) : 0; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
        if ( $id ) { SubmissionDetailPage::render( $id ); return; }
        $filters = $this->filters();
        $page = isset( $_GET['paged'] ) ? max( 1, absint( $_GET['paged'] ) ) : 1; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
        $result = SubmissionService::query( $filters, $page, 25 );
        $forms = Repository::all(); $assignees = SubmissionService::assignees(); $tags = TagService::all(); $statuses = SubmissionService::statuses(); $priorities = SubmissionService::priorities();
        $default_status = WorkflowService::default_status(); $top_priority = WorkflowService::highest_priority(); $review_status = WorkflowService::is_valid( 'status', 'needs_review' ) ? 'needs_review' : '';
        $has_filters = '' !== $filters['search'] || '' !== $filters['status'] || 0 !== $filters['form_id'] || '' !== $filters['assigned_to'] || '' !== $filters['priority'] || 0 !== $filters['tag_id'] || '' !== $filters['date_from'] || '' !== $filters['date_to'];
        ?>
        <div class="wrap bfcamel-crm-admin">
            <div class="bfcamel-crm-page-title"><div><h1><?php esc_html_e( 'Submissions', 'bfcamel-crm' ); ?></h1><p class="description"><?php esc_html_e( 'Search, filter and manage incoming submissions.', 'bfcamel-crm' ); ?></p></div><?php if(current_user_can('bfcamel_crm_export_data')): ?><div class="bfcamel-crm-actions"><?php foreach(array('csv'=>__('Export CSV','bfcamel-crm'),'xlsx'=>__('Export XLSX','bfcamel-crm')) as $format=>$label): $args=array_merge(array('action'=>'bfcamel_crm_export','type'=>'submissions','format'=>$format,'s'=>$filters['search']),array_diff_key($filters,array('search'=>true))); $url=wp_nonce_url(add_query_arg($args,admin_url('admin-post.php')),'bfcamel_crm_export_submissions_'.$format); ?><a class="button" href="<?php echo esc_url($url); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></div><?php endif; ?></div>

            <div class="bfcamel-crm-quick-views">
                <a class="button<?php echo !$has_filters?' button-primary':''; ?>" href="<?php echo esc_url(admin_url('admin.php?page=bfcamel-crm-submissions')); ?>"><?php esc_html_e('All submissions','bfcamel-crm'); ?></a>
                <a class="button<?php echo (string)get_current_user_id()===(string)$filters['assigned_to']?' button-primary':''; ?>" href="<?php echo esc_url(add_query_arg(array('page'=>'bfcamel-crm-submissions','assigned_to'=>get_current_user_id()),admin_url('admin.php'))); ?>"><?php esc_html_e('My submissions','bfcamel-crm'); ?></a>
                <a class="button<?php echo $default_status===$filters['status']?' button-primary':''; ?>" href="<?php echo esc_url(add_query_arg(array('page'=>'bfcamel-crm-submissions','status'=>$default_status),admin_url('admin.php'))); ?>"><?php echo esc_html( WorkflowService::label( 'status', $default_status ) ); ?></a>
                <a class="button<?php echo $top_priority===$filters['priority']?' button-primary':''; ?>" href="<?php echo esc_url(add_query_arg(array('page'=>'bfcamel-crm-submissions','priority'=>$top_priority),admin_url('admin.php'))); ?>"><?php echo esc_html( WorkflowService::label( 'priority', $top_priority ) ); ?></a>
                <a class="button<?php echo '0'===(string)$filters['assigned_to']?' button-primary':''; ?>" href="<?php echo esc_url(add_query_arg(array('page'=>'bfcamel-crm-submissions','assigned_to'=>'0'),admin_url('admin.php'))); ?>"><?php esc_html_e('Unassigned','bfcamel-crm'); ?></a>
                <?php if ( $review_status && $review_status !== $default_status ) : ?><a class="button<?php echo $review_status===$filters['status']?' button-primary':''; ?>" href="<?php echo esc_url(add_query_arg(array('page'=>'bfcamel-crm-submissions','status'=>$review_status),admin_url('admin.php'))); ?>"><?php echo esc_html( WorkflowService::label( 'status', $review_status ) ); ?></a><?php endif; ?>
            </div>

            <form method="get" class="bfcamel-crm-filters"><input type="hidden" name="page" value="bfcamel-crm-submissions"><div class="bfcamel-crm-filter-search"><label class="screen-reader-text" for="bfcamel-crm-search"><?php esc_html_e('Search submissions','bfcamel-crm'); ?></label><input id="bfcamel-crm-search" type="search" name="s" value="<?php echo esc_attr($filters['search']); ?>" placeholder="<?php echo esc_attr__('Search by ID, name, email, phone or form data','bfcamel-crm'); ?>"></div>
            <select name="status"><option value=""><?php esc_html_e('All statuses','bfcamel-crm'); ?></option><?php foreach($statuses as $v=>$l): ?><option value="<?php echo esc_attr($v); ?>" <?php selected($filters['status'],$v); ?>><?php echo esc_html($l); ?></option><?php endforeach; ?></select>
            <select name="form_id"><option value="0"><?php esc_html_e('All forms','bfcamel-crm'); ?></option><?php foreach($forms as $form): ?><option value="<?php echo esc_attr($form->id); ?>" <?php selected($filters['form_id'],$form->id); ?>><?php echo esc_html($form->name); ?></option><?php endforeach; ?></select>
            <select name="assigned_to"><option value="" <?php selected($filters['assigned_to'],''); ?>><?php esc_html_e('All responsible employees','bfcamel-crm'); ?></option><option value="0" <?php selected((string)$filters['assigned_to'],'0'); ?>><?php esc_html_e('Unassigned','bfcamel-crm'); ?></option><?php foreach($assignees as $user): ?><option value="<?php echo esc_attr($user->ID); ?>" <?php selected((string)$filters['assigned_to'],(string)$user->ID); ?>><?php echo esc_html($user->display_name); ?></option><?php endforeach; ?></select>
            <select name="priority"><option value=""><?php esc_html_e('All priorities','bfcamel-crm'); ?></option><?php foreach($priorities as $v=>$l): ?><option value="<?php echo esc_attr($v); ?>" <?php selected($filters['priority'],$v); ?>><?php echo esc_html($l); ?></option><?php endforeach; ?></select>
            <select name="tag_id"><option value="0"><?php esc_html_e('All tags','bfcamel-crm'); ?></option><?php foreach($tags as $tag): ?><option value="<?php echo esc_attr($tag->id); ?>" <?php selected($filters['tag_id'],$tag->id); ?>><?php echo esc_html($tag->name); ?></option><?php endforeach; ?></select>
            <label class="bfcamel-crm-date-filter"><span><?php esc_html_e('From','bfcamel-crm'); ?></span><input type="date" name="date_from" value="<?php echo esc_attr($filters['date_from']); ?>"></label><label class="bfcamel-crm-date-filter"><span><?php esc_html_e('To','bfcamel-crm'); ?></span><input type="date" name="date_to" value="<?php echo esc_attr($filters['date_to']); ?>"></label><button type="submit" class="button button-primary"><?php esc_html_e('Filter','bfcamel-crm'); ?></button><a class="button" href="<?php echo esc_url(admin_url('admin.php?page=bfcamel-crm-submissions')); ?>"><?php esc_html_e('Reset','bfcamel-crm'); ?></a></form>
            <?php if(isset($_GET['bulk_updated'])): // phpcs:ignore WordPress.Security.NonceVerification.Recommended ?><div class="notice notice-success is-dismissible"><p><?php esc_html_e('Selected submissions updated.','bfcamel-crm'); ?></p></div><?php endif; ?>
            <p class="bfcamel-crm-results-count"><?php echo esc_html(sprintf(__('Found: %d','bfcamel-crm'),$result['total'])); ?></p>
            <?php $this->pagination($result,'top'); ?>
            <?php if(current_user_can('bfcamel_crm_edit_submissions')): ?>
            <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="bfcamel-crm-bulk-form"><input type="hidden" name="action" value="bfcamel_crm_bulk_submissions"><?php wp_nonce_field('bfcamel_crm_bulk_submissions'); ?><div class="bfcamel-crm-bulk-bar"><select name="bulk_action"><option value=""><?php esc_html_e('Bulk actions','bfcamel-crm'); ?></option><option value="status"><?php esc_html_e('Set status','bfcamel-crm'); ?></option><option value="priority"><?php esc_html_e('Set priority','bfcamel-crm'); ?></option><option value="assigned_to"><?php esc_html_e('Set responsible','bfcamel-crm'); ?></option><option value="add_tags"><?php esc_html_e('Add tags','bfcamel-crm'); ?></option><option value="remove_tags"><?php esc_html_e('Remove tags','bfcamel-crm'); ?></option></select><select name="bulk_status"><option value=""><?php esc_html_e('Choose status','bfcamel-crm'); ?></option><?php foreach($statuses as $v=>$l): ?><option value="<?php echo esc_attr($v); ?>"><?php echo esc_html($l); ?></option><?php endforeach; ?></select><select name="bulk_priority"><option value=""><?php esc_html_e('Choose priority','bfcamel-crm'); ?></option><?php foreach($priorities as $v=>$l): ?><option value="<?php echo esc_attr($v); ?>"><?php echo esc_html($l); ?></option><?php endforeach; ?></select><select name="bulk_assigned_to"><option value="0"><?php esc_html_e('Unassigned','bfcamel-crm'); ?></option><?php foreach($assignees as $user): ?><option value="<?php echo esc_attr($user->ID); ?>"><?php echo esc_html($user->display_name); ?></option><?php endforeach; ?></select><input type="text" name="bulk_tags" placeholder="<?php echo esc_attr__('Tags, separated by commas','bfcamel-crm'); ?>"><button class="button"><?php esc_html_e('Apply','bfcamel-crm'); ?></button></div><div class="bfcamel-crm-panel bfcamel-crm-panel--table"><?php $this->table($result['rows'],true); ?></div></form>
            <?php else: ?><div class="bfcamel-crm-panel bfcamel-crm-panel--table"><?php $this->table($result['rows'],false); ?></div><?php endif; ?>
            <?php $this->pagination($result,'bottom'); ?>
        </div><?php
    }

    public function update_submission(){ $this->guard('bfcamel_crm_edit_submissions'); SubmissionDetailPage::update(); }
    public function add_note(){ $this->guard('bfcamel_crm_edit_submissions'); $id=isset($_POST['submission_id'])?absint($_POST['submission_id']):0; check_admin_referer('bfcamel_crm_add_submission_note_'.$id); if(!SubmissionService::get($id)) wp_die(esc_html__('Submission not found.','bfcamel-crm')); $r=NoteService::add('submission',$id,isset($_POST['note'])?wp_unslash($_POST['note']):'',get_current_user_id()); if(is_wp_error($r)) wp_die(esc_html($r->get_error_message()),esc_html__('Could not save note','bfcamel-crm'),array('back_link'=>true)); wp_safe_redirect(admin_url('admin.php?page=bfcamel-crm-submissions&id='.$id.'&note_added=1')); exit; }
    public function bulk_submissions(){ $this->guard('bfcamel_crm_edit_submissions'); check_admin_referer('bfcamel_crm_bulk_submissions'); $ids=(array)($_POST['submission_ids']??array()); $action=isset($_POST['bulk_action'])?sanitize_key($_POST['bulk_action']):''; $value=''; if('status'===$action)$value=$_POST['bulk_status']??''; elseif('priority'===$action)$value=$_POST['bulk_priority']??''; elseif('assigned_to'===$action)$value=$_POST['bulk_assigned_to']??0; elseif(in_array($action,array('add_tags','remove_tags'),true))$value=wp_unslash($_POST['bulk_tags']??''); else wp_die(esc_html__('Choose a bulk action.','bfcamel-crm'),'',array('back_link'=>true)); $r=SubmissionService::bulk_apply($ids,$action,$value,get_current_user_id()); if(is_wp_error($r))wp_die(esc_html($r->get_error_message()),esc_html__('Could not update submissions','bfcamel-crm'),array('back_link'=>true)); wp_safe_redirect(admin_url('admin.php?page=bfcamel-crm-submissions&bulk_updated=1')); exit; }

    private function table($rows,$checkboxes){ $default_priority=WorkflowService::default_priority(); ?><div class="bfcamel-crm-table-scroll"><table class="widefat striped bfcamel-crm-table bfcamel-crm-submissions-table"><thead><tr><?php if($checkboxes): ?><td class="check-column"><input class="bfcamel-crm-select-all" type="checkbox"></td><?php endif; ?><th>ID</th><th><?php esc_html_e('Form','bfcamel-crm'); ?></th><th><?php esc_html_e('Contact','bfcamel-crm'); ?></th><th><?php esc_html_e('Status','bfcamel-crm'); ?></th><th><?php esc_html_e('Priority','bfcamel-crm'); ?></th><th><?php esc_html_e('Responsible','bfcamel-crm'); ?></th><th><?php esc_html_e('Tags','bfcamel-crm'); ?></th><th><?php esc_html_e('Received','bfcamel-crm'); ?></th></tr></thead><tbody><?php if(!$rows): ?><tr><td colspan="<?php echo $checkboxes?9:8; ?>"><?php esc_html_e('No submissions yet.','bfcamel-crm'); ?></td></tr><?php endif; foreach((array)$rows as $row): $priority=$row->priority?:$default_priority; ?><tr><?php if($checkboxes): ?><th class="check-column"><input type="checkbox" name="submission_ids[]" value="<?php echo esc_attr($row->id); ?>"></th><?php endif; ?><td><strong><a href="<?php echo esc_url(admin_url('admin.php?page=bfcamel-crm-submissions&id='.absint($row->id))); ?>">#<?php echo esc_html($row->id); ?></a></strong></td><td><?php echo esc_html($row->form_name?:'#'.$row->form_id); ?></td><td><?php echo esc_html($row->contact_name?:('conflict'===$row->contact_sync_status?__('Needs review','bfcamel-crm'):'—')); ?></td><td><span class="bfcamel-crm-badge bfcamel-crm-badge--<?php echo esc_attr(sanitize_html_class($row->status)); ?>"><?php echo esc_html(SubmissionService::status_label($row->status)); ?></span></td><td><span class="bfcamel-crm-priority bfcamel-crm-priority--<?php echo esc_attr(sanitize_html_class($priority)); ?>"><?php echo esc_html(SubmissionService::priority_label($priority)); ?></span></td><td><?php echo esc_html($row->assignee_name?:__('Unassigned','bfcamel-crm')); ?></td><td><?php $this->tags($row->tag_names); ?></td><td><?php echo esc_html(mysql2date(get_option('date_format').' '.get_option('time_format'),$row->submitted_at)); ?></td></tr><?php endforeach; ?></tbody></table></div><?php }
    private function tags($names){ $items=array_filter(array_map('trim',explode(',',(string)$names))); if(!$items){echo '—';return;} foreach($items as $name) echo '<span class="bfcamel-crm-tag">'.esc_html($name).'</span> '; }
    private function pagination($result,$position){ if($result['total_pages']<=1)return; $base=remove_query_arg('paged'); $base=add_query_arg('paged','%#%',$base); $links=paginate_links(array('base'=>$base,'format'=>'','current'=>$result['page'],'total'=>$result['total_pages'],'prev_text'=>'&lsaquo;','next_text'=>'&rsaquo;')); if($links) echo '<div class="tablenav bfcamel-crm-pagination--'.esc_attr($position).'"><div class="tablenav-pages">'.wp_kses_post($links).'</div></div>'; }
    private function filters(){ return array('search'=>isset($_GET['s'])?sanitize_text_field(wp_unslash($_GET['s'])):'','status'=>isset($_GET['status'])?sanitize_key($_GET['status']):'','form_id'=>isset($_GET['form_id'])?absint($_GET['form_id']):0,'assigned_to'=>isset($_GET['assigned_to'])?sanitize_text_field(wp_unslash($_GET['assigned_to'])):'','priority'=>isset($_GET['priority'])?sanitize_key($_GET['priority']):'','tag_id'=>isset($_GET['tag_id'])?absint($_GET['tag_id']):0,'date_from'=>isset($_GET['date_from'])?sanitize_text_field(wp_unslash($_GET['date_from'])):'','date_to'=>isset($_GET['date_to'])?sanitize_text_field(wp_unslash($_GET['date_to'])):''); // phpcs:ignore WordPress.Security.NonceVerification.Recommended
    }
    private function guard($cap){ if(!current_user_can($cap))wp_die(esc_html__('You do not have permission to access this page.','bfcamel-crm')); if(!Schema::is_current())wp_die(esc_html(Schema::readiness_message()),esc_html__('CRM database update required','bfcamel-crm'),array('back_link'=>true)); }
}
